# Autogenerated by devscripts/update-version.py

__version__ = '2025.01.29.110229'

RELEASE_GIT_HEAD = '57c717fee4bfbc9309845bbb48901b72e4b69304'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'Turning-Chinese/yt-dlp-cn'

ORIGIN = 'Turning-Chinese/yt-dlp-cn'

_pkg_version = '2025.01.29.110229'
